from enum import IntEnum


class Error(IntEnum):
  LOGIN_FAILED = 1
  INVALID_ARGUMENT = 2
  TIMESHEET_MISSING = 3
  TIMESHEET_EXISTS = 4
  TIMESHEET_SUBMITTED = 5
  UNPARSABLE_DATE = 6
  CONFIG_ERROR = 7
